version: '3.8'

services:
  db:
    image: postgres:13-trixie
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata: