services:
  postgres:
    image: postgres:13-trixie
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  cassandra:
    image: cassandra:5-jammy
    container_name: cassandra
    env_file:
      - .env
    environment:
      - CASSANDRA_SEEDS=cassandra
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    mem_limit: 2g
    ports:
      - "9042:9042" 
    volumes:
      - cassandradata:/var/lib/cassandra

  cassandra-2:
    image: cassandra:5-jammy
    container_name: cassandra-2
    env_file:
      - .env
    environment:
      - CASSANDRA_SEEDS=cassandra
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    mem_limit: 2g
    ports:
      - "9043:9042" 
    volumes:
      - cassandra2data:/var/lib/cassandra

  cassandra-3:
    image: cassandra:5-jammy
    container_name: cassandra-3
    env_file:
      - .env
    environment:
      - CASSANDRA_SEEDS=cassandra
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    mem_limit: 2g
    ports:
      - "9044:9042" 
    volumes:
      - cassandra3data:/var/lib/cassandra

  api:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    image: tvergilio/motown-house:latest
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8080
    restart: unless-stopped

volumes:
  pgdata:
  cassandradata:
  cassandra2data:
  cassandra3data:

