services:
  postgres:
    image: postgres:13-trixie
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  cassandra:
    image: cassandra:5-jammy
    container_name: cassandra
    env_file:
      - .env
    ports:
      - "9042:9042" 
    volumes:
      - cassandradata:/var/lib/cassandra

  app:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata:
  cassandradata:
